mysql:
  build: .
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: my_blog
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: my_blog
    TZ: "Asia/Tokyo"
  ports:
    - 3306:3306
  volumes:
    - ./data:/var/lib/mysql
